name: Move pdf document
on: [push]
jobs:
  build-typst:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Typst
        uses: lvignoli/typst-action@main
        with:
          source_file: LectureNotes/main.typ
      - name: Copy pdf file
        run: mkdir -p github_deploy && cp LectureNotes/main.pdf github_deploy
      - name: Release
        if: startsWith(github.ref, 'refs/tags/') # Only create a release when pushing to a tag
        uses: softprops/action-gh-release@v1
        with:
          files: github_deploy/main.pdf
      - name: Deploy on orphan branch
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./github_deploy
          publish_branch: pdf
          force_orphan: true
